/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-01-01 20:13:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.thumbnail;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kh.board.model.vo.*;
import com.kh.member.model.vo.Member;

public final class thumbnailListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/thumbnail/../common/menubar.jsp", Long.valueOf(1608914483390L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.kh.board.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Board> list = (ArrayList<Board>)request.getAttribute("list");


      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.outer{\r\n");
      out.write("\t\twidth:1000px;\r\n");
      out.write("\t\theight:700px;\r\n");
      out.write("\t\tbackground:black;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tmargin:auto;\r\n");
      out.write("\t\tmargin-top:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.listArea{\r\n");
      out.write("\t\twidth:760px;\r\n");
      out.write("\t\theight:550px;\r\n");
      out.write("\t\tmargin:auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.thumbnail{\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t\twidth:220px;\r\n");
      out.write("\t\tborder:1px solid white;\r\n");
      out.write("\t\tmargin:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.thumbnail:hover{\r\n");
      out.write("\t\topacity:0.7;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");
	String msg = (String)session.getAttribute("msg");
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction loginValidate(){\r\n");
      out.write("\t\tif($(\"#userId\").val().trim().length==0){\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\t$(\"#userId\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#userPwd\").val().trim().length==0){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t$(\"#userPwd\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tbackground:url('");
      out.print(request.getContextPath() );
      out.write("/resources/images/city1.PNG') no-repeat; \r\n");
      out.write("\t\tbackground-size:cover;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 로그인 폼 관련 스타일*/\r\n");
      out.write("\t#loginForm, #userInfo{float:right;}\r\n");
      out.write("\t.btns button{border-radius:5px;}\r\n");
      out.write("\t#enrollBtn, #mypageBtn{background-color:yellowgreen;}\r\n");
      out.write("\t#loginBtn, #logoutBtn{background-color:orangered;}\r\n");
      out.write("\t#userInfo a{text-decoration:none;color:black;}\r\n");
      out.write("\t\r\n");
      out.write("\t/*네비게이션 스타일*/\r\n");
      out.write("\t.navWrap{background-color:black; width:100%; height:50px}\r\n");
      out.write("\t.navWrap>.nav{width:600px;margin:auto;}\r\n");
      out.write("\t.menu{text-align:center;color:white;font-weight:bold;width:150px;height:50px;display:table-cell;font-size:20px;vertical-align:middle;}\r\n");
      out.write("\t.menu:hover{background-color:darkgray;}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar msg = \"");
      out.print(msg);
      out.write("\";\r\n");
      out.write("\t\tif(msg!=\"null\"){\r\n");
      out.write("\t\t\talert(msg);\r\n");
      out.write("\t\t\t");
session.removeAttribute("msg");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1 align=\"center\">Welcome JSP World!</h1>\r\n");
      out.write("\t<div class=\"loginArea\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
if(loginUser==null){ 
      out.write("\r\n");
      out.write("\t\t<!-- 1_1. 로그인 관련 폼 만들기 (로그인 기능 처리하기) -->\r\n");
      out.write("\t\t<form id=\"loginForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/login.me\" method=\"post\" onsubmit=\"return loginValidate();\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"userId\" style=\"color:white;\">아이디 : </label></th>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"userId\" type=\"text\" name=\"userId\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"userPwd\" style=\"color:white;\">비밀번호 : </label></th>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"userPwd\" type=\"text\" name=\"userPwd\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\t\t\t\t<!-- 3_1. 회원가입 처리하기 -->\r\n");
      out.write("\t\t\t\t<!-- <button id=\"loginBtn\" type=\"submit\">로그인</button> -->\r\n");
      out.write("\t\t\t\t<button id=\"loginBtn\" type=\"submit\">로그인</button>\r\n");
      out.write("\t\t\t\t<button id=\"enrollBtn\" type=\"button\" onclick=\"enrollPage();\">회원가입</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t<div id=\"userInfo\">\r\n");
      out.write("\t\t\t<b>");
      out.print(loginUser.getUserName() );
      out.write("님</b> 의 방문을 환영합니다.\r\n");
      out.write("\t\t\t<br><br>\r\n");
      out.write("\t\t\t<div class = \"btns\" align=\"center\">\r\n");
      out.write("\t\t\t<!--마이페이지, 로그아웃-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/myPage.me\">마이페이지</a>\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/logOut.me\">로그아웃</a>\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t//회원가입 \r\n");
      out.write("\t\t\tfunction enrollPage(){\r\n");
      out.write("\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/enrollForm.me\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<br clear=\"both\">\r\n");
      out.write("\t\t<div class = \"navWrap\">\r\n");
      out.write("\t\t\t<div class = \"nav\">\r\n");
      out.write("\t\t\t\t<div class=\"menu\" onclick=\"goMain();\">Home</div>\r\n");
      out.write("\t\t\t\t<div class=\"menu\" onclick=\"goNotice();\">공지사항</div>\r\n");
      out.write("\t\t\t\t<div class=\"menu\" onclick=\"goBoard();\">게시판</div>\r\n");
      out.write("\t\t\t\t<div class=\"menu\" onclick=\"goThumbnail();\">사진게시판</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tfunction goMain(){\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction goNotice(){\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/list.no\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction goBoard(){\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction goThumbnail(){\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/list.th\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"outer\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<h2 align=\"center\">사진 게시판</h2>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"listArea\">\r\n");
      out.write("\t\t\t");
for(Board b : list){ 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"thumbnail\" align=\"center\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(b.getBoardNo());
      out.write("\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(contextPath );
      out.write("/resources/board_upfiles/");
      out.print( b.getTitleImg() );
      out.write("\" width=\"200px\" height=\"150px\"> <br>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tNo.");
      out.print( b.getBoardNo() );
      out.write(' ');
      out.write(' ');
      out.print(b.getBoardTitle() );
      out.write(" <br>\r\n");
      out.write("\t\t\t\t\t조회수 : ");
      out.print(b.getCount() );
      out.write("\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br><br>\r\n");
      out.write("\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 if(loginUser != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<button onclick=\"location.href='");
      out.print(contextPath );
      out.write("/insertForm.th'\">작성하기</button>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t$(\".thumbnail\").click(function(){\r\n");
      out.write("\t\t\t\t\tvar bId = $(this).children().eq(0).val();\r\n");
      out.write("\t\t\t\t\tlocation.href=\"");
      out.print(contextPath);
      out.write("/detail.th?bId=\" + bId;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
